from prompts.vision_extraction import (
    VISION_EXTRACTION_SYSTEM_PROMPT,
    VISION_EXTRACTION_USER_PROMPT_TEMPLATE,
)

__all__ = [
    "VISION_EXTRACTION_SYSTEM_PROMPT",
    "VISION_EXTRACTION_USER_PROMPT_TEMPLATE",
]
